test

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/dash
 VERSION=0.0.0
 
 CFG_CMDLINE=
@@ -10,15 +10,35 @@ HOSTDIR=
 SRCPKGS=
 XSC=
 _append=""
-RCV=`command -v xbps-checkvers 2>/dev/null`
+RCV=$(command -v xbps-checkvers 2>/dev/null)
 RCV_F="repo-checkvers.txt"
 TOBUILD=
-_TOBUILD=
 USAGE="Usage: $0 [-a cross-arch] [-CN] [-d|-m|-h dir]"
 
-[ -f $RCV ] || {
-	printf "ERROR: The 'xbps-checkvers' was not found in the PATH.\n"
-	exit 1
+: ${RCV:?"ERROR: The 'xbps-checkvers' was not found in the PATH.\n"}
+
+getlink() {
+	p=${1##*/}
+	target=$(readlink "$SRCPKGS/$p")
+	[ $? -eq 0 ] && [ -n "$target" ] && p=$target
+	echo "$p"
+}
+
+gendeps() {
+	echo "gendeps $1" >&2
+	printf 'built/%s:' "$1"
+	$XSC show-build-deps "$1" 2>/dev/null | sed -e 's|[<>].*$||g' | \
+		while read -r d; do
+			[ "$d" = "=" ] && continue
+			realdep=$(getlink "$d")
+			if [ -e "tobuild/$realdep" ]; then
+				touch "./deps/$realdep"
+				printf ' %s' "deps/$realdep"
+			else
+				printf ' %s' "built/$realdep"
+			fi
+		done
+	printf "\n"
 }
 
 while getopts a:Cc:d:Nm:th:v OPT; do
@@ -43,8 +63,8 @@ while getopts a:Cc:d:Nm:th:v OPT; do
 		exit 0
 		;;
 	C)
-		rm -rf tobuild built
-		rm -f *.txt Makefile
+		rm -rf tobuild built deps
+		rm -f *.txt *.d
 		exit 0
 		;;
 	d)
@@ -99,108 +119,45 @@ RCV_CMD_LINE="$RCV --distdir=${DISTDIR} ${*}"
 printf "INFO: Getting list of updates, please wait...\n"
 printf "INFO: Running '$RCV_CMD_LINE' (${CROSS_ARCH:-native}) ...\n"
 
-[ -f $RCV_F ] && _append="-a"
-$RCV_CMD_LINE | tee ${_append} $RCV_F
-rval=${PIPESTATUS[0]}
-if [ $rval -ne 0 ]; then
-	echo "ERROR: xbps-checkvers exited with an error: $rval"
+$RCV_CMD_LINE >>"$RCV_F" || {
+	echo "ERROR: xbps-checkvers exited with an error: $?"
 	exit 1
-fi
-grep pkgname $RCV_F | awk '{ print $2 }' > pkgs.txt
+}
+
+grep pkgname "$RCV_F" | awk '{ print $2 }' > pkgs.txt
 
 printf "INFO: Creating source targets...\n"
-rm -rf tobuild built
-mkdir -p tobuild built
-for p in `cat pkgs.txt`; do
-	if [ -f "$SRCPKGS/$p/template" ]; then
-		$XSC show-avail $p 2>/dev/null
-		if [ $? -eq 0 ]; then
-			touch tobuild/$p
-		fi
-	fi
-done
-
-_TOBUILD="`find tobuild -type f`"
-
-concat() {
-	local found=0
-	for tb in $TOBUILD; do
-		if [ "$1" = "$tb" ]; then
-			found=1
-			break
-		fi
-	done
-	if [ $found -eq 0 ]; then
-		TOBUILD="$TOBUILD $1"
-	fi
-}
-
-getlink() {
-	local p="`basename $1`"
-	local target="`readlink $SRCPKGS/$p`"
-	if [ $? -eq 0 -a -n "$target" ]; then
-		p=$target
-	fi
-	echo $p
-}
+rm -rf tobuild built deps
+mkdir -p tobuild built deps
 
 printf "INFO: Generating a proper list (without subpkgs)...\n"
-for tb in $_TOBUILD; do
-	concat "`getlink $tb`"
-done
+while read -r p; do
+	[ -f "$SRCPKGS/$p/template" ] || continue
+	$XSC show-avail "$p" 2>/dev/null || continue
+	realdep=$(getlink "$p")
+	[ -e "./tobuild/$realdep" ] && continue
+	touch "./tobuild/$realdep"
+	TOBUILD="$TOBUILD $realdep"
+done < pkgs.txt
 
-printf "INFO: Removing old Makefile (if any)...\n"
-[ -f Makefile ] && rm -f Makefile
-touch Makefile
-
-
-printf "INFO: Generating standard targets...\n"
-printf "# Generated by configure, do not modify.\n\n"		>> Makefile
-printf "PKGS = $TOBUILD\n"					>> Makefile
-printf "TOBUILD = \$(patsubst %%,tobuild/%%,\$(PKGS))\n"	>> Makefile
-printf "BUILT = \$(patsubst tobuild/%%,built/%%,\$(TOBUILD))\n\n"	>> Makefile
-printf "all: \$(BUILT)\n"					>> Makefile
-printf "\t@echo \"[Done]\"\n\n"					>> Makefile
-printf "print_pkgs:\n"						>> Makefile
-printf "\t@echo \$(PKGS)\n\n"					>> Makefile
-printf "built/%%: tobuild/%%\n"					>> Makefile
-printf "\t@echo \"[xbps-src]\t\${@F}\"\n"			>> Makefile
-printf "\t@( $XSC pkg \${@F}; rval=\$\$?; [ \$\$rval -eq 2 ] && exit 0 || exit \$\$rval )\n"	>> Makefile
-printf "\t@touch \$@\n"						>> Makefile
-printf "\t@rm tobuild/\${@F}\n\n"				>> Makefile
-
+printf "INFO: Generate config...\n"
+cat <<EOF >config.mk
+DISTDIR		= ${DISTDIR}
+HOSTDIR		= ${HOSTDIR}
+MASTERDIR	= ${MASTERDIR}
+EOF
 
 printf "INFO: Finding and adding dependencies...\n"
-printf "# Dependencies\n"					>> Makefile
-for p in $TOBUILD; do
-	deps=
-	sedcmd="s|[<>].*\$||g"
-	_deps="`$XSC show-build-deps $p 2>/dev/null| sed -e \"$sedcmd\"`"
-	if [ -z "${_deps}" ]; then
-		continue
-	fi
-	for d in $_deps; do
-		found=0
-		realdep=`getlink $d`
-		for _p in $TOBUILD; do
-			if [ "$_p" = "$realdep" ]; then
-				found=1
-				break;
-			fi
-		done
-		if [ $found -gt 0 ]; then
-			deps="$deps built/$realdep"
-		fi
-	done
-	printf "built/$p: $deps\n"				>> Makefile
+
+for f in ./tobuild/*; do
+	[ "$f" = '*' ] && continue
+	[ -x "$f" ] && continue
+	gendeps "${f##*/}" >>deps.d
 done
 
-printf "\n"							>> Makefile
-printf "clean:\n"						>> Makefile
-printf "\t@rm -f built/*\n"					>> Makefile
-printf "\t@echo \"[Clean]\"\n\n"				>> Makefile
-printf ".PHONY: all print_pkgs clean\n"				>> Makefile
-
-printf "INFO: 'Makefile' generated.\n"
-printf "INFO: Type 'make'\n"
-exit 0
+for f in ./deps/*; do
+	[ "$f" = '*' ] && continue
+	[ -x "$f" ] && continue
+	gendeps "${f##*/}" >>deps.d
+	chmod +x "$f"
+done
